//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPost
    {
        public int PostID { get; set; }
        public string PostText { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
